version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    container_name: 'redis_url_shortener'
    command: redis-server
    ports:
      - '6379:6379'

  web:
    build: .
    restart: always
    container_name: 'url_shortener'
    command: poetry run uvicorn --host 0.0.0.0 --port 8080 api.main:app --reload
    volumes:
      - .:/code
    ports:
      - '8080:8080'
